name: Penguin e2e Tests

on: [workflow_dispatch]

jobs:
  e2e-Test-Cycle:
    runs-on: macos-latest
    environment: Cypress
    env:
      cypress_email: ${{ secrets.CYPRESS_EMAIL }}
      cypress_password: ${{ secrets.CYPRESS_PASSWORD }}
    steps:
      - name: Install Packages
        run: |
          echo $cypress_email
          echo $cypress_password
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Packages
        run: npm install
        
      - name: e2e Tests
        uses: cypress-io/github-action@v2
        with:
          build: npx cypress run --spec cypress/integration/login/PNAV-6215_Verify_that_user_is_on_Sign_In_page.ts  --browser chrome --config-file=cypress.config.ts || true
        continue-on-error: true
      - name: Copy Test Screenshots
        run: |
          mkdir public
          mkdir -p cypress/screenshots
          cp -r cypress/screenshots public/screenshots
      # - name: Merge test results into one
      #   run: npm run merge-reports
      # - name: Generate HTML report
      #   run: npm run generate-htmlreport
      # - name: Deploy report page
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     user_name: "github-actions[bot]"
      #     user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: public
