name: Penguin e2e Tests

on: [workflow_dispatch]

jobs:
  e2e-Test-Cycle:
    runs-on: macos-latest
    environment: Cypress
    env:
      cypress_email: ${{ secrets.CYPRESS_EMAIL }}
      cypress_password: ${{ secrets.CYPRESS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Packages
        run: npm install
      
      - name: e2e Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
        continue-on-error: true
    
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: ignore
          path: cypress/screenshots
      
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
    
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
